#!/bin/bash

# Script para generar archivos de aplicación
# Uso: ./generate-app-files.sh [nodejs|python] [app-name]

set -e

LANGUAGE="${1:-nodejs}"
APP_NAME="${2:-my-app}"

echo "🚀 Generando archivos para aplicación $LANGUAGE"
echo "================================================"
echo ""

# Crear directorio temporal
TEMP_DIR="generated-app-$APP_NAME"
mkdir -p "$TEMP_DIR"

if [ "$LANGUAGE" == "nodejs" ]; then
    echo "📦 Generando archivos Node.js..."
    
    # package.json
    cat > "$TEMP_DIR/package.json" << EOF
{
  "name": "$APP_NAME",
  "version": "1.0.0",
  "description": "Application generated by Backstage",
  "main": "index.js",
  "scripts": {
    "start": "node index.js",
    "dev": "nodemon index.js",
    "test": "echo \\"No tests yet\\" && exit 0"
  },
  "keywords": [],
  "author": "",
  "license": "MIT",
  "dependencies": {
    "express": "^4.18.2"
  },
  "devDependencies": {
    "nodemon": "^3.0.1"
  }
}
EOF

    # index.js
    cat > "$TEMP_DIR/index.js" << 'EOF'
const express = require('express');
const app = express();
const PORT = process.env.PORT || 3000;

// Middleware
app.use(express.json());

// Routes
app.get('/', (req, res) => {
  res.json({
    message: 'Hello World!',
    app: process.env.APP_NAME || 'my-app',
    environment: process.env.ENVIRONMENT || 'dev',
    timestamp: new Date().toISOString()
  });
});

app.get('/health', (req, res) => {
  res.json({
    status: 'healthy',
    uptime: process.uptime(),
    timestamp: new Date().toISOString()
  });
});

// Start server
app.listen(PORT, '0.0.0.0', () => {
  console.log(`🚀 Server listening on port ${PORT}`);
  console.log(`✅ Health check: http://localhost:${PORT}/health`);
});

// Graceful shutdown
process.on('SIGTERM', () => {
  console.log('SIGTERM signal received: closing HTTP server');
  process.exit(0);
});

process.on('SIGINT', () => {
  console.log('SIGINT signal received: closing HTTP server');
  process.exit(0);
});
EOF

    # healthcheck.js
    cat > "$TEMP_DIR/healthcheck.js" << 'EOF'
const http = require('http');

const options = {
  host: 'localhost',
  port: process.env.PORT || 3000,
  path: '/health',
  timeout: 2000
};

const request = http.request(options, (res) => {
  console.log(`Health check status: ${res.statusCode}`);
  if (res.statusCode === 200) {
    process.exit(0);
  } else {
    process.exit(1);
  }
});

request.on('error', (err) => {
  console.error('Health check failed:', err);
  process.exit(1);
});

request.end();
EOF

    # .dockerignore
    cat > "$TEMP_DIR/.dockerignore" << 'EOF'
node_modules
npm-debug.log
.git
.gitignore
README.md
.env
.DS_Store
EOF

    echo "✅ Archivos Node.js generados"

elif [ "$LANGUAGE" == "python" ]; then
    echo "🐍 Generando archivos Python..."
    
    # requirements.txt
    cat > "$TEMP_DIR/requirements.txt" << 'EOF'
flask==3.0.0
gunicorn==21.2.0
EOF

    # app.py
    cat > "$TEMP_DIR/app.py" << 'EOF'
from flask import Flask, jsonify
from datetime import datetime
import os

app = Flask(__name__)

@app.route('/')
def hello():
    return jsonify({
        'message': 'Hello World!',
        'app': os.environ.get('APP_NAME', 'my-app'),
        'environment': os.environ.get('ENVIRONMENT', 'dev'),
        'timestamp': datetime.now().isoformat()
    })

@app.route('/health')
def health():
    return jsonify({
        'status': 'healthy',
        'timestamp': datetime.now().isoformat()
    })

if __name__ == '__main__':
    port = int(os.environ.get('PORT', 8000))
    print(f'🚀 Server listening on port {port}')
    print(f'✅ Health check: http://localhost:{port}/health')
    app.run(host='0.0.0.0', port=port)
EOF

    # healthcheck.py
    cat > "$TEMP_DIR/healthcheck.py" << 'EOF'
import http.client
import sys
import os

port = int(os.environ.get('PORT', 8000))

try:
    conn = http.client.HTTPConnection('localhost', port, timeout=2)
    conn.request('GET', '/health')
    response = conn.getresponse()
    
    if response.status == 200:
        print(f'Health check passed: {response.status}')
        sys.exit(0)
    else:
        print(f'Health check failed: {response.status}')
        sys.exit(1)
except Exception as e:
    print(f'Health check error: {e}')
    sys.exit(1)
finally:
    conn.close()
EOF

    # .dockerignore
    cat > "$TEMP_DIR/.dockerignore" << 'EOF'
__pycache__
*.pyc
*.pyo
*.pyd
.Python
.git
.gitignore
README.md
.env
.DS_Store
venv/
EOF

    echo "✅ Archivos Python generados"

else
    echo "❌ Lenguaje no soportado: $LANGUAGE"
    echo "Usa: nodejs o python"
    exit 1
fi

echo ""
echo "================================================"
echo "✅ Archivos generados en: $TEMP_DIR/"
echo ""
echo "📋 Archivos creados:"
ls -la "$TEMP_DIR/"
echo ""
echo "🚀 Próximos pasos:"
echo ""
echo "1. Copia los archivos a tu repositorio:"
echo "   cp $TEMP_DIR/* /path/to/your/repo/"
echo ""
echo "2. O si estás en el directorio del repo:"
echo "   cp $TEMP_DIR/* ."
echo ""
echo "3. Commit y push:"
echo "   git add ."
echo "   git commit -m 'feat: Add application source code'"
echo "   git push origin main"
echo ""
echo "4. El workflow se ejecutará automáticamente"
echo ""
